### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by ststeiger** [jamesej/lynicon#3]
The below files are missing in the git-repository. 
Either supply them, or remove them from the project. 
Also, remove the update-report files from the git-repository.

Lynicon.AutoTests
 - App.config

Lynicon.Site
 - Web.config

**Comment by jamesej** [comment]
Many thanks for getting in touch about this issue, the relevant files have now been added/removed. Do email to let us know how you get on using Lynicon at info@lynicon.com.
