### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aaroncalderon** [jamesej/lynicon#4]
On the README.md file, third paragraph, you state that "it is open source" however, the Fair Source license [FAQ](https://fair.io/#how-is-the-fair-source-license-similar-to-or-different-from-open-source-licenses) states that it is not open source.

So I am confused.

Can you please clarify?

Thanks in advance.

**Comment by jamesej** [comment]
The Fair Source FAQ is technically incorrect as open source simply means the source is publically available, it does not mean free under all circumstances. But for clarification where the Fair Source license refers to 'number of users' for Lynicon this means number of developers, not number of users of any site you may create. So Lynicon is free unless it is being used by a dev team of more than 10 users.

**Comment by aaroncalderon** [comment]
Thanks. That clarified a lot. 

Will it make sense to put this on the readme?
